### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by warrenbuckley** [andreabbondanza/vscode-iisee#1]
Hello @andreabbondanza 
I was looking for my extension on the VS Code Gallery & notice that you too have also built an IIS Extension for VS Code.

I was wondering if you would be interested in collaborating together on this perhaps?
https://github.com/warrenbuckley/IIS-Express-Code

Cheers,
Warren :)

**Comment by andreabbondanza** [comment]
Hi @warrenbuckley 
Sorry for the late answer, I'm a lot busy at work in these days. How do you think to start this collaboration? I'm asking because I'm a bit "new" on github and still I don't have the best knowledge of the platform.

**Comment by warrenbuckley** [comment]
Well we could merge some of your ideas & work as PR's into my existing extension so that there is one super freaking awesome IIS VS Code Extension rather than fragment with two separate packages.

https://help.github.com/articles/about-pull-requests/

**Comment by andreabbondanza** [comment]
Honestly I made this extension just for work needs, and I placed it on the market just to help people with my same problems.
I don't feel to take a commitment in this way, also because I'll update the extension only when I need and I'll not follow it like my other regular repository (I'm too busy with work).
However thanks for the proposal and feels free to use this code in the best way you think. :)
PS: Thank you for the tip about github, I didn't know how works the pull request.
